decorator:
  datasource:
    p6spy:
      enable-logging: false # p6spy enable
      multiline: true
      logging: slf4j  # sysout, slf4j, file, custom

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/prevel
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        highlight_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

auth:
  key:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
    expiration-time: 86400000

---
tour:
  api:
    key: ${TOUR_API_KEY}
    url: https://apis.data.go.kr
    suburl: /B551011/KorService1